version: "3.5"
services:
  mongo:
    image: mongo:latest
    volumes:
      - "../CMS-mongo-data:/data/db"
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - proxy
    restart: always

  hapi-fhir-jpaserver-start:
    image: sean2525/hapi-fhir-jpaserver-starter:latest
    container_name: hapi-fhir-jpaserver-starter
    restart: on-failure
    networks:
      - proxy
    ports:
      - "127.0.0.1:8080:8080"
      
  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    networks:
      - proxy
    volumes:
      - "../CMS-mysql-data:/var/lib/mysql"

networks:
  proxy:
