name: Python package

on:
  push:
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install all dependencies
        run: |
          pip install pipenv
          pipenv --python python3 sync -d
      - name: Test with pytest
        run: |
          pipenv run python -m pytest --cov=./ --cov-report xml --cov-config=.coveragerc tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
